# app/config/packages/config.local.yaml

framework:
  templating: { engines: [twig] }
fos_user:
  db_driver:  orm
  firewall_name:  main
  user_class: FOS\UserBundle\Model\User`
  from_email: 
    address:  "justinbeckh@gmail.com"
    sender_name:  "Justin"